
export enum MapChunkType {
    UnknownType = 0,

    /// Save Game
    SaveGameCommentText = 250,
    SaveGameGeneralInformation = 130,
    SaveGameMapLandscape = 200,
    SaveGameFog = 135,
    SaveGameLogo = 136,
    SaveGameCurrent = 132,
    SaveGameFutureEvents = 142,
    SaveGameEffects = 143,
    SaveGameAI = 150,
    SaveGameES = 180,
    SaveGameMapObjects = 170,
    SaveGameDecoObjects = 164,
    SaveGamePiles = 163,
    SaveGameBuildings = 162,
    SaveGameSettlers = 161,
    SaveGameVehicles = 166,
    SaveGameFlyingEntities = 168,
    SaveGameAnimals = 165,
    SaveGameScript = 131,
    SaveGamePlayers = 140,
    SaveGameStatistic1 = 133,
    SaveGameStatistic2 = 137,
    SaveGameGroups = 134,
    SaveGameTraders = 167,

    /// Game Map
    MapGeneralInformation = 1,
    MapPlayerInformation = 2,
    MapTeamInformation = 3,
    MapPreview = 4,
    MapUnknown5 = 5,
    MapObjects = 6,
    MapSettlers = 7,
    MapBuildings = 8,
    MapStacks = 9,
    MapUnknown10 = 10,
    MapQuestText = 11,
    MapQuestTip = 12,
    MapLandscape = 13,
}
